export const OrderStatus = {
  CART: "CART",
  IN_REVIEW: "IN_REVIEW",
  PURCHASED: "PURCHASED",
  COMPLETED: "COMPLETED",
  BUSINESS_CANCELED: "BUSINESS_CANCELED",
  CONSUMER_CANCELED: "CONSUMER_CANCELED",
  CONSUMER_CANCELED_REFUNDED: "CONSUMER_CANCELED_REFUNDED",
  CONSUMER_CANCELED_NOT_REFUNDED: "CONSUMER_CANCELED_NOT_REFUNDED",
  SYSTEM_CANCELED: "SYSTEM_CANCELED",
  CART_EXPIRED: "CART_EXPIRED",
  IN_REVIEW_EXPIRED: "IN_REVIEW_EXPIRED",
};
