export const AddressActionType = {
  CREATE_ADDRESS_REQUESTED: 'CREATE_ADDRESS_REQUESTED',
  CREATE_ADDRESS_SUCCESS: 'CREATE_ADDRESS_SUCCESS',
  CREATE_ADDRESS_ERROR: 'CREATE_ADDRESS_ERROR',

  ARCHIVE_ADDRESS_REQUESTED: 'ARCHIVE_ADDRESS_REQUESTED',
  ARCHIVE_ADDRESS_SUCCESS: 'ARCHIVE_ADDRESS_SUCCESS',
  ARCHIVE_ADDRESS_ERROR: 'ARCHIVE_ADDRESS_ERROR',
};

export const AddressKeys = {
  Address: 'address',
};
