export const AuthenticationActionType = {
  SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',

  SIGN_OUT_REQUESTED: 'SIGN_OUT_REQUESTED',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',

  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  CONFIRMATION_SIGN_UP_REQUESTED: 'CONFIRMATION_SIGN_UP_REQUESTED',
  CONFIRMATION_SIGN_UP_SUCCESS: 'CONFIRMATION_SIGN_UP_SUCCESS',
  CONFIRMATION_SIGN_UP_ERROR: 'CONFIRMATION_SIGN_UP_ERROR',

  GET_CURRENT_SESSION_REQUESTED: 'GET_CURRENT_SESSION_REQUESTED',
  GET_CURRENT_SESSION_SUCCESS: 'GET_CURRENT_SESSION_SUCCESS',
  GET_CURRENT_SESSION_ERROR: 'GET_CURRENT_SESSION_ERROR',

  GET_USER_CREDENTIALS_REQUESTED: 'GET_USER_CREDENTIALS_REQUESTED',
  GET_USER_CREDENTIALS_SUCCESS: 'GET_USER_CREDENTIALS_SUCCESS',
  GET_USER_CREDENTIALS_ERROR: 'GET_USER_CREDENTIALS_ERROR',

  FORGOT_PASSWORD_REQUESTED: 'FORGOT_PASSWORD_REQUESTED',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',

  FORGOT_PASSWORD_SUBMIT_REQUESTED: 'FORGOT_PASSWORD_SUBMIT_REQUESTED',
  FORGOT_PASSWORD_SUBMIT_SUCCESS: 'FORGOT_PASSWORD_SUBMIT_SUCCESS',
  FORGOT_PASSWORD_SUBMIT_ERROR: 'FORGOT_PASSWORD_SUBMIT_ERROR',

  CHANGE_PASSWORD_REQUESTED: 'CHANGE_PASSWORD_REQUESTED',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',

  GET_AUTHENTICATED_USER_REQUESTED: 'GET_AUTHENTICATED_USER_REQUESTED',
  GET_AUTHENTICATED_USER_SUCCESS: 'GET_AUTHENTICATED_USER_SUCCESS',
  GET_AUTHENTICATED_USER_ERROR: 'GET_AUTHENTICATED_USER_ERROR',
};

export const AuthenticationKeys = {
  Authentication: 'authentication',
};
