export const BusinessActionType = {
  GET_BUSINESSES_BY_DOMAIN_REQUESTED: 'GET_BUSINESSES_BY_DOMAIN_REQUESTED',
  GET_BUSINESSES_BY_DOMAIN_SUCCESS: 'GET_BUSINESSES_BY_DOMAIN_SUCCESS',
  GET_BUSINESSES_BY_DOMAIN_ERROR: 'GET_BUSINESSES_BY_DOMAIN_ERROR',
};

export const BusinessKeys = {
  Business: 'business',
};
