export const CardActionType = {
  CREATE_CARD_PAYMENT_METHOD_REQUESTED: 'CREATE_CARD_PAYMENT_METHOD_REQUESTED',
  CREATE_CARD_PAYMENT_METHOD_SUCCESS: 'CREATE_CARD_PAYMENT_METHOD_SUCCESS',
  CREATE_CARD_PAYMENT_METHOD_ERROR: 'CREATE_CARD_PAYMENT_METHOD_ERROR',

  CREATE_CONSUMER_CARD_REQUESTED: 'CREATE_CONSUMER_CARD_REQUESTED',
  CREATE_CONSUMER_CARD_SUCCESS: 'CREATE_CONSUMER_CARD_SUCCESS',
  CREATE_CONSUMER_CARD_ERROR: 'CREATE_CONSUMER_CARD_ERROR',

  ARCHIVE_CONSUMER_CARD_REQUESTED: 'ARCHIVE_CONSUMER_CARD_REQUESTED',
  ARCHIVE_CONSUMER_CARD_SUCCESS: 'ARCHIVE_CONSUMER_CARD_SUCCESS',
  ARCHIVE_CONSUMER_CARD_ERROR: 'ARCHIVE_CONSUMER_CARD_ERROR',
};

export const CardKeys = {
  Card: 'card',
};
