export const CartActionType = {
  ADD_OFFER_TO_CART: 'ADD_OFFER_TO_CART',
  ADD_PLAN_TO_CART: 'ADD_PLAN_TO_CART',

  REMOVE_PLAN_ORDER_IN_CART: 'REMOVE_PLAN_ORDER_IN_CART',

  CLEAR_BUSINESS_SCHEDULE_IN_CART: 'CLEAR_BUSINESS_SCHEDULE_IN_CART',

  CLEAR_PLAN_ORDERS_IN_CART: 'CLEAR_PLAN_ORDERS_IN_CART',
  CLEAR_PRODUCT_ORDERS_IN_CART: 'CLEAR_PRODUCT_ORDERS_IN_CART',

  GET_ACTIVE_SCHEDULES_IN_CART: 'GET_ACTIVE_SCHEDULES_IN_CART',
  GET_ACTIVE_ORDERS: 'GET_ACTIVE_ORDERS',
  GET_ACTIVE_PLAN_ORDERS: 'GET_ACTIVE_PLAN_ORDERS',

  GET_CHECKOUT_TYPE: 'GET_CHECKOUT_TYPE',

  SET_ACTIVE_PLAN_ORDERS_IN_CART: 'SET_ACTIVE_PLAN_ORDERS_IN_CART',

  SET_SCHEDULE_OFFERS: 'SET_SCHEDULE_OFFERS',

  SET_SELECTED_CART: 'SET_SELECTED_CART',
};

export const CartKeys = {
  Cart: 'cart',
};
