export const ConsumerActionType = {
  GET_CONSUMER_REQUESTED: 'GET_CONSUMER_REQUESTED',
  GET_CONSUMER_SUCCESS: 'GET_CONSUMER_SUCCESS',
  GET_CONSUMER_ERROR: 'GET_CONSUMER_ERROR',

  CREATE_CONSUMER_REQUESTED: 'CREATE_CONSUMER_REQUESTED',
  CREATE_CONSUMER_SUCCESS: 'CREATE_CONSUMER_SUCCESS',
  CREATE_CONSUMER_ERROR: 'CREATE_CONSUMER_ERROR',

  CREATE_GUEST_CONSUMER_REQUESTED: 'CREATE_GUEST_CONSUMER_REQUESTED',
  CREATE_GUEST_CONSUMER_SUCCESS: 'CREATE_GUEST_CONSUMER_SUCCESS',
  CREATE_GUEST_CONSUMER_ERROR: 'CREATE_GUEST_CONSUMER_ERROR',

  UPDATE_CONSUMER_REQUESTED: 'UPDATE_CONSUMER_REQUESTED',
  UPDATE_CONSUMER_SUCCESS: 'UPDATE_CONSUMER_SUCCESS',
  UPDATE_CONSUMER_ERROR: 'UPDATE_CONSUMER_ERROR',

  UPLOAD_CONSUMER_IMAGE_REQUESTED: 'UPLOAD_CONSUMER_IMAGE_REQUESTED',
  UPLOAD_CONSUMER_IMAGE_SUCCESS: 'UPLOAD_CONSUMER_IMAGE_SUCCESS',
  UPLOAD_CONSUMER_IMAGE_ERROR: 'UPLOAD_CONSUMER_IMAGE_ERROR',

  REMOVE_CONSUMER_IMAGE_REQUESTED: 'REMOVE_CONSUMER_IMAGE_REQUESTED',
  REMOVE_CONSUMER_IMAGE_SUCCESS: 'REMOVE_CONSUMER_IMAGE_SUCCESS',
  REMOVE_CONSUMER_IMAGE_ERROR: 'REMOVE_CONSUMER_IMAGE_ERROR',
};

export const ConsumerKeys = {
  Consumer: 'Consumer',
};
