export const OrderItemActionType = {
  CREATE_ORDER_ITEM_REQUESTED: 'CREATE_ORDER_ITEM_REQUESTED',
  CREATE_ORDER_ITEM_SUCCESS: 'CREATE_ORDER_ITEM_SUCCESS',
  CREATE_ORDER_ITEM_ERROR: 'CREATE_ORDER_ITEM_ERROR',

  UPDATE_ORDER_ITEM_REQUESTED: 'UPDATE_ORDER_ITEM_REQUESTED',
  UPDATE_ORDER_ITEM_SUCCESS: 'UPDATE_ORDER_ITEM_SUCCESS',
  UPDATE_ORDER_ITEM_ERROR: 'UPDATE_ORDER_ITEM_ERROR',

  DELETE_ORDER_ITEM_REQUESTED: 'DELETE_ORDER_ITEM_REQUESTED',
  DELETE_ORDER_ITEM_SUCCESS: 'DELETE_ORDER_ITEM_SUCCESS',
  DELETE_ORDER_ITEM_ERROR: 'DELETE_ORDER_ITEM_ERROR',
};

export const OrderItemKeys = {
  OrderItem: 'orderItem',
};
