export const OrderActionType = {
  GET_ORDERS_REQUESTED: 'GET_ORDERS_REQUESTED',
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_ERROR: 'GET_ORDERS_ERROR',

  GET_CONSUMER_ORDER_REQUESTED: 'GET_CONSUMER_ORDER_REQUESTED',
  GET_CONSUMER_ORDER_SUCCESS: 'GET_CONSUMER_ORDER_SUCCESS',
  GET_CONSUMER_ORDER_ERROR: 'GET_CONSUMER_ORDER_ERROR',

  GET_ORDER_REQUESTED: 'GET_ORDER_REQUESTED',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_ERROR: 'GET_ORDER_ERROR',

  CREATE_ORDERS_REQUESTED: 'CREATE_ORDERS_REQUESTED',
  CREATE_ORDERS_SUCCESS: 'CREATE_ORDERS_SUCCESS',
  CREATE_ORDERS_ERROR: 'CREATE_ORDERS_ERROR',

  UPDATE_ORDER_REQUESTED: 'UPDATE_ORDER_REQUESTED',
  UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
  UPDATE_ORDER_ERROR: 'UPDATE_ORDER_ERROR',

  DELETE_ORDER_REQUESTED: 'DELETE_ORDER_REQUESTED',
  DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
  DELETE_ORDER_ERROR: 'DELETE_ORDER_ERROR',

  TRANSITION_ORDER_REQUESTED: 'TRANSITION_ORDER_REQUESTED',
  TRANSITION_ORDER_SUCCESS: 'TRANSITION_ORDER_SUCCESS',
  TRANSITION_ORDER_ERROR: 'TRANSITION_ORDER_ERROR',

  CALCULATE_ORDER_REQUESTED: 'CALCULATE_ORDER_REQUESTED',
  CALCULATE_ORDER_SUCCESS: 'CALCULATE_ORDER_SUCCESS',
  CALCULATE_ORDER_ERROR: 'CALCULATE_ORDER_ERROR',

  APPLY_COUPON_TO_ORDER_REQUESTED: 'APPLY_COUPON_TO_ORDER_REQUESTED',
  APPLY_COUPON_TO_ORDER_SUCCESS: 'APPLY_COUPON_TO_ORDER_SUCCESS',
  APPLY_COUPON_TO_ORDER_ERROR: 'APPLY_COUPON_TO_ORDER_ERROR',

  APPLY_DELIVERY_ADDRESS_TO_ORDER_REQUESTED: 'APPLY_DELIVERY_ADDRESS_TO_ORDER_REQUESTED',
  APPLY_DELIVERY_ADDRESS_TO_ORDER_SUCCESS: 'APPLY_DELIVERY_ADDRESS_TO_ORDER_SUCCESS',
  APPLY_DELIVERY_ADDRESS_TO_ORDER_ERROR: 'APPLY_DELIVERY_ADDRESS_TO_ORDER_ERROR',

  APPLY_CARD_TO_ORDER_REQUESTED: 'APPLY_CARD_TO_ORDER_REQUESTED',
  APPLY_CARD_TO_ORDER_SUCCESS: 'APPLY_CARD_TO_ORDER_SUCCESS',
  APPLY_CARD_TO_ORDER_ERROR: 'APPLY_CARD_TO_ORDER_ERROR',
};

export const OrderKeys = {
  Order: 'orders',
};
