export const SubscriptionInvoiceActionType = {
  GET_SUBSCRIPTION_INVOICES_REQUESTED: 'GET_SUBSCRIPTION_INVOICES_REQUESTED',
  GET_SUBSCRIPTION_INVOICES_SUCCESS: 'GET_SUBSCRIPTION_INVOICES_SUCCESS',
  GET_SUBSCRIPTION_INVOICES_ERROR: 'GET_SUBSCRIPTION_INVOICES_ERROR',
};

export const SubscriptionInvoiceKeys = {
  SubscriptionInvoice: 'subscription_invoice',
};
