export const SubscriptionActionType = {
  CREATE_SUBSCRIPTION_REQUESTED: 'CREATE_SUBSCRIPTION_REQUESTED',
  CREATE_SUBSCRIPTION_SUCCESS: 'CREATE_SUBSCRIPTION_SUCCESS',
  CREATE_SUBSCRIPTION_ERROR: 'CREATE_SUBSCRIPTION_ERROR',

  ARCHIVE_SUBSCRIPTION_REQUESTED: 'ARCHIVE_SUBSCRIPTION_REQUESTED',
  ARCHIVE_SUBSCRIPTION_SUCCESS: 'ARCHIVE_SUBSCRIPTION_SUCCESS',
  ARCHIVE_SUBSCRIPTION_ERROR: 'ARCHIVE_SUBSCRIPTION_ERROR',

  UPDATE_SUBSCRIPTION_REQUESTED: 'UPDATE_SUBSCRIPTION_REQUESTED',
  UPDATE_SUBSCRIPTION_SUCCESS: 'UPDATE_SUBSCRIPTION_SUCCESS',
  UPDATE_SUBSCRIPTION_ERROR: 'UPDATE_SUBSCRIPTION_ERROR',

  GET_SUBSCRIPTIONS_REQUESTED: 'GET_SUBSCRIPTIONS_REQUESTED',
  GET_SUBSCRIPTIONS_SUCCESS: 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_ERROR: 'GET_SUBSCRIPTIONS_ERROR',
};

export const SubscriptionKeys = {
  Subscription: 'subscription',
};
