export const TransportationActionType = {
  GET_BUSINESSES_TRANSPORTATION_REQUESTED: 'GET_BUSINESSES_TRANSPORTATION_REQUESTED',
  GET_BUSINESSES_TRANSPORTATION_SUCCESS: 'GET_BUSINESSES_TRANSPORTATION_SUCCESS',
  GET_BUSINESSES_TRANSPORTATION_ERROR: 'GET_BUSINESSES_TRANSPORTATION_ERROR',

  GET_TRANSPORTATION_TYPE: 'GET_TRANSPORTATION_TYPE',

  SET_TRANSPORTATION_TYPE: 'SET_TRANSPORTATION_TYPE',
  SET_SELECTED_ADDRESS_ID: 'SET_SELECTED_ADDRESS_ID',
};

export const TransportationKeys = {
  Transportation: 'transportation',
};
